Repository googleinterns/open-sesame, pull requests merged in 2020-08, with the labels that each got.

#160 Use stretched link.
  src/main/webapp/mentors.js
Labels: cla: yes

#159 Add deployment steps to the readme & firebase SDK import change
  README.md
  src/main/webapp/signup.html
Labels: cla: yes, documentation

#151 Add backend support for filters to project queries from servlet.
  pom.xml
  src/main/java/com/google/opensesame/projects/ProjectEntity.java
  src/main/java/com/google/opensesame/projects/ProjectQuery.java
  src/main/java/com/google/opensesame/projects/QueryFilter.java
  src/main/java/com/google/opensesame/servlets/ProjectFullServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectNameServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewServlet.java
  src/main/java/com/google/opensesame/util/ErrorResponse.java
  src/main/java/com/google/opensesame/util/ServletValidationException.java
  src/test/java/com/google/opensesame/projects/ProjectEntityTest.java
  src/test/java/com/google/opensesame/projects/ProjectQueryTest.java
  src/test/java/com/google/opensesame/projects/QueryFilterTest.java
Labels: cla: no

#163 Make GitHub throw an exception when it runs out of API calls
  src/main/java/com/google/opensesame/github/GitHubGetter.java
  src/main/java/com/google/opensesame/util/RateLimitExceededException.java
Labels: cla: yes, enhancement

#164 Remove repeated JS testing info from readme
  README.md
Labels: cla: yes
