Repository googleinterns/open-sesame, pull requests merged in 2020-07, with the labels that each got.

#32 Add some robustness to mentor class; create person class.
  src/main/java/com/google/opensesame/servlets/MentorBuilder.java
  src/main/java/com/google/opensesame/servlets/MentorObject.java
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/servlets/PersonBuilder.java
  src/main/java/com/google/opensesame/servlets/PersonObject.java
Labels: cla: no

#33 Populate Affiliations with Dashboard.js
  package.json
  src/main/webapp/dashboard.css
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
Labels: cla: yes

#31 Add navbar to homepage.
  src/main/webapp/index.html
Labels: cla: yes

#38 Add mentors page to navbar and add navbar to mentors page.
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/mentors.html
  src/main/webapp/mentors.js
Labels: cla: yes

#45 Mentors edits
  src/main/java/com/google/opensesame/servlets/MentorBuilder.java
  src/main/java/com/google/opensesame/servlets/MentorObject.java
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/servlets/PersonBuilder.java
  src/main/java/com/google/opensesame/servlets/PersonObject.java
Labels: cla: no

#44 Remove jsx-dashboard command from package.json
  package.json
Labels: cla: yes

#34 Add backend support for project previews
  pom.xml
  src/main/java/com/google/opensesame/projects/ProjectPreview.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewsServlet.java
  src/test/java/com/google/opensesame/projects/ProjectPreviewTest.java
Labels: cla: yes

#40 Add tests to the GitHubGetter
  src/main/java/com/google/opensesame/github/GitHubGetter.java
  src/test/java/com/google/opensesame/github/GitHubGetterTest.java
Labels: cla: no

#47 Fix JSX relative imports
  .gitignore
  package.json
  src/main/webapp/index.html
  src/main/webapp/js/checkTesting.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/components/NavbarLink.js
  src/main/webapp/mentors.html
  src/main/webapp/projects.html
Labels: cla: yes

#53 Address eslint errors
  src/main/webapp/dashboard.js
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/mentors.js
Labels: cla: yes

#43 Add a test for associating a project with a mentor object.
  pom.xml
  src/test/java/com/google/opensesame/MentorTest.java
Labels: cla: yes

#46 Consolidate builder
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/servlets/PersonBuilder.java
Labels: cla: no

#50 Add fetch support on projects preview frontend
  src/main/webapp/js/fetch_handler.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/ProjectTagList.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/projects_search.js
  src/main/webapp/js/projects/react/prop_types.js
Labels: cla: no

#52 Add basic Github authorization with Oauth
  src/main/webapp/authorization.js
  src/main/webapp/index.html
Labels: cla: no

#49 Add detail to mentors page.
  src/main/java/com/google/opensesame/servlets/PersonObject.java
  src/main/webapp/mentors.js
Labels: cla: yes

#56 Add basic authentication servlet
  src/main/java/com/google/opensesame/auth/AuthServlet.java
Labels: cla: no

#57 Add React authorization button to navbar
  src/main/webapp/index.html
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/style.css
Labels: cla: yes

#58 Add basic sign up form frontend.
  src/main/java/com/google/opensesame/auth/AuthServlet.java
  src/main/webapp/index.html
  src/main/webapp/signup.html
Labels: cla: yes

#61 Create first iteration of mentor sign-up form.
  src/main/webapp/dashboard.html
  src/main/webapp/mentor_form.html
Labels: cla: yes

#60 Add projects datastore support
  src/main/java/com/google/opensesame/projects/ProjectDatastore.java
  src/main/java/com/google/opensesame/projects/ProjectEntity.java
  src/main/java/com/google/opensesame/projects/ProjectPreviewData.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewsServlet.java
  src/test/java/com/google/opensesame/projects/ProjectPreviewDataTest.java
Labels: cla: no

#59 Link UserServlet to Datastore
  src/main/java/com/google/opensesame/servlets/PersonObject.java
  src/main/java/com/google/opensesame/servlets/UserServlet.java
  src/main/webapp/user.js
  src/test/java/com/google/opensesame/MentorTest.java
Labels: cla: yes

#66 Make function naming consistent.
  src/main/webapp/mentors.js
Labels: cla: yes

#64 Add tests to the fetch error handler
  README.md
  package-lock.json
  package.json
  src/main/webapp/js/fetch_handler.test.js
Labels: cla: yes

#65 add --fix argument to ESLint
  .eslintrc
  .github/workflows/formatting.yaml
  package-lock.json
  package.json
  src/main/webapp/authorization.js
  src/main/webapp/dashboard.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/fetch_handler.test.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/ProjectTagList.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/mentors.js
  src/main/webapp/user.js
Labels: cla: yes

#67 Handle invalid mentor form input.
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/webapp/mentor_form.html
  src/main/webapp/mentors.js
Labels: cla: no

#71 Use standard fetch error handler.
  src/main/webapp/mentors.html
  src/main/webapp/mentors.js
Labels: cla: yes

#68 Fix JS tests with fetch
  src/main/webapp/js/checkTesting.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/tests/Navbar.test.js
  src/main/webapp/js/fetch_handler.js
  src/main/webapp/js/fetch_handler.test.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
Labels: cla: yes

#73 Get User information from GitHub
  src/main/java/com/google/opensesame/servlets/MentorBuilder.java
  src/main/java/com/google/opensesame/servlets/MentorObject.java
  src/main/java/com/google/opensesame/servlets/PersonBuilder.java
  src/main/java/com/google/opensesame/servlets/PersonObject.java
  src/main/java/com/google/opensesame/servlets/UserServlet.java
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
  src/main/webapp/user.js
  src/test/java/com/google/opensesame/MentorTest.java
Labels: cla: yes

#69 Add frontend signup functionality
  src/main/java/com/google/opensesame/auth/AuthServlet.java
  src/main/webapp/css/signup.css
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/projects.html
  src/main/webapp/signup.html
  src/main/webapp/signup.js
Labels: cla: no

#72 Make ErrorResponse extend error and remove JSON formatter
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/fetch_handler.js
  src/main/webapp/js/fetch_handler.test.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
Labels: cla: yes

#75 Create helper function for API errors
  src/main/java/com/google/opensesame/util/ErrorResponse.java
Labels: cla: no

#84 Merging code to master that was intended to be merged with master
  src/main/java/com/google/opensesame/auth/AuthServlet.java
  src/main/java/com/google/opensesame/util/ErrorResponse.java
  src/main/webapp/css/signup.css
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/fetch_handler.js
  src/main/webapp/js/fetch_handler.test.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/mentors.js
  src/main/webapp/projects.html
  src/main/webapp/signup.html
  src/main/webapp/signup.js
Labels: cla: no

#83 Java linter patch: Lint auto-commits
  .github/workflows/formatting.yaml
Labels: cla: yes

#86 Add Error Handling to the Signup and User Dashboard pipeline
  src/main/java/com/google/opensesame/servlets/UserServlet.java
  src/main/webapp/signup.js
  src/main/webapp/user.js
Labels: cla: no

#96 Patch UserServlet Compilation Error
  src/main/java/com/google/opensesame/servlets/UserServlet.java
Labels: cla: no

#79 Integrate changes to mentor search and mentor form pages in one js file.
  src/main/webapp/mentors.js
Labels: cla: yes

#77 Complete projects datastore integration
  src/main/java/com/google/opensesame/projects/ProjectDatastore.java
  src/main/java/com/google/opensesame/projects/ProjectEntity.java
  src/main/java/com/google/opensesame/projects/ProjectPreviewData.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewsServlet.java
  src/test/java/com/google/opensesame/projects/ProjectPreviewDataTest.java
Labels: cla: no

#87 Add email field to user signup
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/signup.html
  src/main/webapp/signup.js
Labels: cla: yes

#89 Fixes for index.html
  src/main/webapp/index.html
Labels: cla: yes

#100 Fix signup.js
  src/main/webapp/signup.js
Labels: cla: yes

#92 Add function to check if a user has a profile with OpenSesame
  src/main/java/com/google/opensesame/servlets/UserServlet.java
Labels: cla: yes

#94 Add Objectify dependency and create mentor and person entity classes.
  pom.xml
  src/main/java/com/google/opensesame/objectify/ObjectifyBootstrapper.java
  src/main/java/com/google/opensesame/objectify/ObjectifyWebFilter.java
  src/main/java/com/google/opensesame/servlets/MentorEntity.java
  src/main/java/com/google/opensesame/servlets/PersonEntity.java
Labels: cla: no

#85 Add expanded project data support to backend
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/servlets/ProjectServlet.java
Labels: cla: no

#114 Projects update
  src/main/java/com/google/opensesame/servlets/MentorEntity.java
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/user/UserEntity.java
  src/main/webapp/mentors.js
Labels: cla: yes

#103 Project breakout page
  src/main/webapp/css/projects.css
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/MentorCard.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/TagList.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/style.css
Labels: cla: no

#98 Add React routing for project frontend.
  .eslintrc
  package-lock.json
  package.json
  src/main/webapp/css/projects.css
  src/main/webapp/js/checkTesting.js
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/DataFetcher.js
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/MentorCard.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/components/TagList.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/projects.html
  src/main/webapp/style.css
Labels: cla: no

#105 Projects objectify
  src/main/java/com/google/opensesame/objectify/ObjectifyBootstrapper.java
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/projects/ProjectDatastore.java
  src/main/java/com/google/opensesame/projects/ProjectEntity.java
  src/main/java/com/google/opensesame/projects/ProjectPreviewData.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewsServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectServlet.java
Labels: cla: no

#116 Projects update
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
Labels: cla: no

#119 Alves mvp cleanup
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/user/UserEntity.java
  src/main/webapp/mentors.html
  src/main/webapp/mentors.js
Labels: cla: no

#120 Remove mailtoui
  src/main/webapp/mentors.js
Labels: cla: yes

#122 Fix eslint errors/warnings.
  src/main/webapp/js/projects/react/components/MentorCard.js
  src/main/webapp/mentors.js
Labels: cla: yes

#125 Mvp edits
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/webapp/mentors.js
Labels: cla: no

#121 Bulk Merge MVP Changes
  src/main/java/com/google/opensesame/auth/AuthServlet.java
  src/main/java/com/google/opensesame/objectify/ObjectifyBootstrapper.java
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/servlets/MentorBuilder.java
  src/main/java/com/google/opensesame/servlets/MentorEntity.java
  src/main/java/com/google/opensesame/servlets/MentorObject.java
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/servlets/PersonBuilder.java
  src/main/java/com/google/opensesame/servlets/PersonEntity.java
  src/main/java/com/google/opensesame/servlets/PersonObject.java
  src/main/java/com/google/opensesame/servlets/UserServlet.java
  src/main/java/com/google/opensesame/user/UserData.java
  src/main/java/com/google/opensesame/user/UserEntity.java
  src/main/webapp/authorization.js
  src/main/webapp/dashboard.css
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/components/NavbarLink.js
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/js/common/react/navbar_prop_types.js
  src/main/webapp/js/common/react/tests/Navbar.test.js
  src/main/webapp/js/common/react/tests/NavbarLink.test.js
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/MentorCard.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/mentors.html
  src/main/webapp/mentors.js
  src/main/webapp/signup.html
  src/main/webapp/signup.js
  src/main/webapp/style.css
  src/main/webapp/user.js
  src/test/java/com/google/opensesame/MentorTest.java
Labels: cla: no

#111 Add authenticated-only links to Navbar
  src/main/webapp/js/common/react/tests/Navbar.test.js
Labels: cla: no

#112 Make the title of the README more clear
  README.md
Labels: cla: yes

#127 Improve Linter documentation
  .github/workflows/LintingAndTestingCI.yaml
  README.md
Labels: cla: yes

#129 Add authentication redirect and add to README
  README.md
  src/main/java/com/google/opensesame/auth/AuthServlet.java
  src/main/webapp/js/auth_check.js
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/js/default_auth_redirect.js
  src/main/webapp/projects.html
  src/main/webapp/sign_in_redirect.html
  src/main/webapp/sign_in_redirect.js
Labels: cla: yes

#132 Remove default exports
  src/main/webapp/js/checkTesting.js
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/DataFetcher.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/components/NavbarLink.js
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/js/common/react/navbar_prop_types.js
  src/main/webapp/js/common/react/tests/Navbar.test.js
  src/main/webapp/js/common/react/tests/NavbarLink.test.js
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/MentorCard.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/components/TagList.js
  src/main/webapp/js/projects/react/projects_search.js
Labels: cla: yes

#131 Create reusable GitHub Object mocks
  src/test/java/com/google/opensesame/mockObjects/MockGHObjects.java
  src/test/java/com/google/opensesame/mockObjects/MockGHObjectsTest.java
Labels: cla: no

#133 Add MailtoUI to project breakout mentor card
  .eslintrc
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/projects.html
Labels: cla: yes

#134 Add MailtoUI to Mentor Page Mentor card.
  src/main/webapp/mentors.js
Labels: cla: yes

#130 Homepage Update.
  src/main/webapp/index.html
  src/main/webapp/style.css
Labels: cla: yes

#126 Consolidate to single project data class and servlet
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/projects/ProjectEntity.java
  src/main/java/com/google/opensesame/projects/ProjectPreviewData.java
  src/main/java/com/google/opensesame/servlets/ProjectFullServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectNameServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectPreviewsServlet.java
  src/main/java/com/google/opensesame/servlets/ProjectServlet.java
  src/main/webapp/dashboard.js
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/mentors.js
Labels: cla: no

#139 Small navbar fixes
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/display_navbar.js
  src/main/webapp/js/common/react/tests/Navbar.test.js
  src/main/webapp/js/common/react/tests/NavbarLink.test.js
Labels: cla: yes

#136 Button
  src/main/webapp/index.html
  src/main/webapp/js/common/react/index.js
Labels: cla: yes

#138 Fix Duplicated ESLint Annotation
  .eslintrc
  .github/workflows/LintingAndTestingCI.yaml
  README.md
  src/main/webapp/authorization.js
Labels: cla: yes

#135 Add mailtoUI to the dashboard
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
Labels: cla: yes

#137 Tweak home page HTML
  src/main/webapp/index.html
  src/main/webapp/style.css
Labels: cla: yes

#145 create GitHub mock object
  src/test/java/com/google/opensesame/mockObjects/MockGHObjects.java
Labels: cla: no, codehealth, documentation

#141 Get ProjectData from the UserServlet
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/java/com/google/opensesame/servlets/UserServlet.java
  src/main/java/com/google/opensesame/user/UserData.java
  src/main/java/com/google/opensesame/user/UserEntity.java
  src/main/webapp/dashboard.js
  src/main/webapp/mentors.js
Labels: cla: yes, codehealth, documentation, enhancement

#140 Add testing to projects frontend
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/common/react/components/DataFetcher.js
  src/main/webapp/js/common/react/components/Navbar.js
  src/main/webapp/js/common/react/components/NavbarLink.js
  src/main/webapp/js/common/react/navbar_prop_types.js
  src/main/webapp/js/projects/react/components/ProjectList.js
  src/main/webapp/js/projects/react/components/ProjectPreview.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/components/TagList.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/js/setTestingGlobals.js
  src/main/webapp/js/tests/ExpandedProject.test.js
  src/main/webapp/js/tests/Navbar.test.js
  src/main/webapp/js/tests/ProjectList.test.js
  src/main/webapp/js/tests/fetch_handler.test.js
Labels: cla: no, codehealth

#148 Make interest tags wrap.
  src/main/webapp/dashboard.js
  src/main/webapp/mentors.js
Labels: cla: yes

#142 Projects backend testing
  pom.xml
  src/test/java/com/google/opensesame/projects/ProjectEntityTest.java
Labels: cla: no, codehealth

#144 Add function for mocking GitHub API interface
  src/main/java/com/google/opensesame/github/GitHubGetter.java
  src/test/java/com/google/opensesame/mockObjects/MockGHObjects.java
Labels: cla: no, codehealth

#147 Add Redirect functionality to the Dashboard page
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
Labels: cla: yes, enhancement

#146 Add tests for UserEntity
  src/main/java/com/google/opensesame/user/UserEntity.java
  src/test/java/com/google/opensesame/user/UserEntityTest.java
Labels: cla: yes, codehealth, documentation, enhancement

#152 Fix null name bug
  src/main/java/com/google/opensesame/user/UserData.java
Labels: bug, cla: yes, documentation

#143 Add tests for the AuthButton
  src/main/webapp/js/common/react/components/AuthButton.js
  src/main/webapp/js/tests/AuthButton.test.js
Labels: cla: no, codehealth

#154 Add repo GitHub link to the project breakout page
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/servlets/ProjectFullServlet.java
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/js/tests/ExpandedProject.test.js
  src/main/webapp/projects.html
Labels: cla: no

#156 Add Test for Dashboard
  src/main/webapp/dashboard.html
  src/main/webapp/dashboard.js
  src/main/webapp/dashboard.test.js
Labels: cla: yes

#149 Mentors Frontend Testing 1
  src/main/webapp/mentors.js
  src/main/webapp/test/mentors.test.js
Labels: cla: yes

#155 Add mentor breakout pages.
  src/main/java/com/google/opensesame/servlets/MentorBreakoutServlet.java
  src/main/java/com/google/opensesame/servlets/MentorsServlet.java
  src/main/webapp/mentor_breakout.html
  src/main/webapp/mentor_breakout.js
  src/main/webapp/mentors.js
Labels: cla: no

#157 Render project README on project breakout page
  .eslintrc
  src/main/java/com/google/opensesame/projects/ProjectData.java
  src/main/java/com/google/opensesame/servlets/ProjectFullServlet.java
  src/main/webapp/css/github-markdown.css
  src/main/webapp/js/projects/react/components/ExpandedProject.js
  src/main/webapp/js/projects/react/components/ProjectsSearch.js
  src/main/webapp/js/projects/react/prop_types.js
  src/main/webapp/js/tests/ExpandedProject.test.js
  src/main/webapp/projects.html
Labels: cla: no

#161 Add a CONTRIBUTING.md file
  .eslintignore
  .github/workflows/LintingAndTestingCI.yaml
  CONTRIBUTING.md
  README.md
  package.json
Labels: cla: yes
